
[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts@v4.9.0=node_modules/@openzeppelin/contracts',
    '@openzeppelin/contracts-upgradeable@v4.9.0=node_modules/@openzeppelin/contracts-upgradeable',
    '@openzeppelin/contracts/utils=node_modules/@openzeppelin/contracts/utils',
    'hardhat=node_modules/hardhat',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
